basler_params:
  -
    name: AcquisitionFrameRate
    type: float
    value: 5.0
  -
    name: ExposureTime
    type: float
    value: 20000.0
  -
    name: AcquisitionMode
    type: enum
    value: Continuous
  -
    name: Gain
    type: float
    value: 1.0
  -
    name: TriggerMode
    type: enum
    value: 'Off'
  -
    name: LineSelector
    type: enum
    value: Line1
